POST http://localhost:8080/sendTransaction
Content-Type: application/json

{
  "hash": "fakehash6",
  "rawTx": "this is a fake raw tx data"
}

###

POST http://localhost:8080/sendTransaction
Content-Type: application/json

{
  "hash": "fakehash7",
  "rawTx": "this is a fake raw tx data"
}

###

POST http://localhost:8080/sendTransaction
Content-Type: application/json

{
  "hash": "fakehash8",
  "rawTx": "this is a fake raw tx data"
}

###

POST http://localhost:8080/sendTransaction
Content-Type: application/json

{
  "hash": "fakehash9",
  "rawTx": "this is a fake raw tx data"
}

###

POST http://localhost:8080/sendTransaction
Content-Type: application/json

{
  "hash": "fakehash10",
  "rawTx": "this is a fake raw tx data"
}

###